# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20160603_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/usrpics/'),
        ),
    ]
