# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20160603_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='/img/dog.png', null=True, upload_to='img/usrpics/'),
        ),
    ]
